CREATE TABLE IF NOT EXISTS socials (
  id SERIAL PRIMARY KEY,
  type SOCIALTYPE NOT NULL,
  value VARCHAR(255) NOT NULL,
  updated_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  deleted_at TIMESTAMPTZ
);
